
server:
    port: 8083
spring:
    application:
        name: book-service


info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8082/eureka/

      
foo: baz
