eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/
    instance:
        hostname: localhost
server:
    port: 8082
spring:
    application:
        name: discovery
